services:
  todo_app:
    image: todo_app:dev
    env_file: .env
    build:
      context: .
      target: dev
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: todo_app
        target: /app/todo_app