name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo_app .
    - run: docker run todo_app
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo Deploy