name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo_app .
    - run: docker run todo_app
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker login -u elliotbarnes -p ${{ secrets.DOCKER_TOKEN }}
    - run: docker build --target prod --tag elliotbarnes/todo-app:prod .
    - run: docker push elliotbarnes/todo-app:prod
    - run: curl -dH -X POST '${{ secrets.WEBHOOK_URL }}'